name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: install ktlint (default)
        uses: ./
      - run: test "$(ktlint --version)" = '0.42.1'

      - name: install ktlint 0.40.0
        uses: ./
        with:
          ktlint_version: 0.40.0
      - run: test "$(ktlint --version)" = '0.40.0'